import os

INFERENCE_INTERVAL_FRAMES  = int(os.environ.get("IRIS_INFERENCE_INTERVAL_FRAMES", "1"))
DETECTION_COOLDOWN_SECONDS = int(os.environ.get("IRIS_DETECTION_COOLDOWN_SECONDS", "3600"))
RECOGNITION_THRESHOLD      = float(os.environ.get("IRIS_RECOGNITION_THRESHOLD", "0.5"))
DETECTION_CONFIDENCE       = float(os.environ.get("IRIS_DETECTION_CONFIDENCE", "0.5"))
EMBEDDING_MODEL            = os.environ.get("IRIS_EMBEDDING_MODEL", "insightface")
