DATA_DIR = "data/"
CONTACTS_DIR = "data/contacts/"
EMBEDDINGS_PATH = "data/embeddings.pkl"
FRAME_QUEUE_MAXSIZE = 5
INFERENCE_INTERVAL_FRAMES = 1
DETECTION_COOLDOWN_SECONDS = 10
DETECTION_CONFIDENCE_THRESHOLD = 0.5
